---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "common.fullname" . }}-api-ingress
  labels:
    app.kubernetes.io/component: {{ include "common.fullname" . }}-api-ingress
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2$3
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/proxy-body-size: 2g
spec:
  tls:
  - hosts:
    - {{required "A valid .Values.ingress.host entry required!" .Values.ingress.host }}
    secretName: wildcard-secret
  rules:
  - host: {{required "A valid .Values.ingress.host entry required!" .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path | quote }}
        backend:
          serviceName: {{ include "common.fullname" . }}-api
          servicePort: 80