apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}-api
  labels:
    app.kubernetes.io/component: "api"
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app.kubernetes.io/component: "api"
    {{- include "common.selectorLabels" . | nindent 4 }}
